# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 18:28
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademiRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atype', models.CharField(choices=[('School Test', 'Student Test'), ('Sport', 'Sport')], max_length=100)),
                ('ascore', models.FloatField()),
                ('adate', models.DateTimeField()),
                ('asubject', models.CharField(max_length=3000)),
                ('afullscore', models.FloatField()),
                ('arank', models.IntegerField()),
                ('anpart', models.IntegerField()),
                ('apartrange', models.CharField(max_length=3000)),
                ('acomment', models.CharField(max_length=3000)),
                ('auser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agsign', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('agsigndate', models.DateField(blank=True, default=None, null=True)),
                ('agservertime', models.DateTimeField(blank=True, default=None, null=True)),
                ('agipaddress', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('aguseragent', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('agaddress', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('agtype', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('agwriter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btitle', models.CharField(max_length=100)),
                ('bcontent', models.CharField(max_length=3000)),
                ('bwrittentime', models.DateTimeField()),
                ('bimg', models.FileField(upload_to='uploads/')),
                ('bwriter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=200)),
                ('cname_ch', models.CharField(max_length=200)),
                ('cdescription', models.CharField(max_length=2000)),
                ('cdescription_ch', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edlname', models.CharField(max_length=200)),
                ('edlname_ch', models.CharField(max_length=200)),
                ('edldescription', models.CharField(max_length=2000)),
                ('edldescription_ch', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exlname', models.CharField(max_length=200)),
                ('exlname_ch', models.CharField(max_length=200)),
                ('exldescription', models.CharField(max_length=2000)),
                ('exldescription_ch', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='HourlyPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hpname', models.CharField(max_length=200)),
                ('hpname_ch', models.CharField(max_length=200)),
                ('hpdescription', models.CharField(max_length=2000)),
                ('hpdescription_ch', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='LengthTimeWorkedEducator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ltwename', models.CharField(max_length=200)),
                ('ltwename_ch', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PostRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preducation', models.CharField(max_length=200)),
                ('probjective', models.CharField(max_length=200)),
                ('prcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexusite.Category')),
                ('preducation_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexusite.EducationLevel')),
                ('prexperience_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexusite.ExperienceLevel')),
                ('prprice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexusite.HourlyPrice')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('birthday', models.DateField(blank=True, default=None, null=True)),
                ('ssn', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('address', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('state', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('zipcode', models.CharField(blank=True, default=0, max_length=5, null=True, verbose_name='ZIP code')),
                ('hrprice', models.FloatField(blank=True, default=None, max_length=20, null=True)),
                ('skill', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('educationbg', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('category', models.CharField(choices=[('Math', 'Math'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology')], default=None, max_length=50, null=True)),
                ('timezone', timezone_field.fields.TimeZoneField(blank=True, default='America/Los_Angeles', null=True)),
                ('country', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('iam', models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher')], default='Student', max_length=30, null=True)),
                ('money', models.FloatField(blank=True, default=0, null=True)),
                ('subject_s', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('grade_s', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('goal_s', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('disability_s', models.NullBooleanField(default=False)),
                ('travel', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Student home', 'Student home'), ('Public place', 'Public place'), ('Online Video Conferencing', 'Online Video Conferencing'), ('On the phone via a secure private line', 'On the phone via a secure private line')], max_length=90, null=True)),
                ('range', models.CharField(blank=True, choices=[('5 miles', '5 miles'), ('10 miles', '10 miles'), ('20 miles', '20 miles'), ('40 miles', '40 miles'), ('Phone or Video', 'Phone or Video')], default='5 miles', max_length=300, null=True)),
                ('tutoringexpskill', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('expertfieldexp', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('professionalaward', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('academicinstitution', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('professionalcertification', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('userimg', models.ImageField(null=True, upload_to='images/')),
                ('completeprofile', models.NullBooleanField(default=False)),
                ('educationlevel', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='nexusite.EducationLevel')),
                ('lengthtimeworkededucator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='nexusite.LengthTimeWorkedEducator')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=200)),
                ('uname_ch', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urname', models.CharField(max_length=200)),
                ('urname_ch', models.CharField(max_length=200)),
                ('urdescription', models.CharField(max_length=2000)),
                ('urdescription_ch', models.CharField(max_length=2000)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='university',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='nexusite.University'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postrequest',
            name='pruser_rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nexusite.UserRating'),
        ),
        migrations.AddField(
            model_name='postrequest',
            name='prwriter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
