# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexusite', '0002_profile_ageverify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ageverify',
            field=models.CharField(blank=True, choices=[('I am the parent of students', 'I am the parent of students'), ('I am a student over the age of 18', 'I am a student over the age of 18'), ('I am a student under the age of 18', 'I am a student under the age of 18')], default=None, max_length=50, null=True),
        ),
    ]
