# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexusite', '0006_profile_servicetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='disability_s',
            field=models.NullBooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
    ]
