# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexusite', '0007_auto_20170828_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='disability_s',
            field=models.NullBooleanField(choices=[(True, 'Yes'), (False, 'No')], default=None),
        ),
    ]
