# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexusite', '0011_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='agreeteacher',
            field=models.NullBooleanField(default=False),
        ),
    ]
